### ISSUE TITLE
AllenNLP version

### ISSUE THREAD

**Issue by nitishgupta** [huminghao16/MTMSN#10]
Which version of AllenNLP was used to train the MTMSN-LARGE model that is released? 

It doesn't work with 0.9 for example. Could you please add a requirements.txt in the repository with the version of packages that works.

**Comment by huminghao16** [comment]
The version of AllenNLP is 0.8.4.
Thanks for your advices! I will add such information into README.

**Comment by nitishgupta** [comment]
Thanks Minghao; I still faced the following issue -- 
The `state_dict` in MTMSN-large checkpoint has keys such as `module.bert.embeddings.word_embeddings.weight` i.e. each containing `module` in the beginning, but the code requires keys like `bert.embeddings.word_embeddings.weight`. 
I was able to load the model by modifying the state_dict -- could you tell a cleaner way of doing this?

**Comment by nitishgupta** [comment]
Thanks! It works with Allennlp 0.8.4
